sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer info -i

script:
  - composer test
